name: fluttr
description: Dart CLI tool which simplifies the setup of new Flutter projects by automatically generating a well-structured folder and file layout,currently tailored for personal use. Suggestions are welcomed to improve this tool making it more valuable for broader audience
version: 1.0.2
repository: https://github.com/Hackman-Adu/fluttr.git

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  pubspec_parse: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  fluttr:
